# Generated by Django 2.0.3 on 2018-03-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20180325_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
