# Generated by Django 2.0.3 on 2018-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
